#!/usr/bin/env Rscript
# ==============================================================================
# Analysis / Figure3.R  --  PLACEHOLDER (made in iTOL, not R)
# ==============================================================================
#
# Submitted Figure 3 (two side-by-side five-ring circular phylogenies for
# ST69 and ST10, with rings for Shell Cluster / Clinicality / Region /
# K-type (ST69) or Year (ST10) / Year) was confirmed BY YOU to have been
# built in iTOL (https://itol.embl.de), not generated by any R script in
# this repository.
#
# This was independently corroborated during reorganisation: no script in
# the repo produces a matching multi-ring circular tree. The two closest
# candidates were checked and ruled out:
#   - `12_fig02-05_ST69_analysis.R`'s own "FIGURE 7: Tree mapping" section
#     (preserved, unmodified, inside Analysis/Supplementary.R's block 17)
#     -- only single-ring, non-circular trees.
#   - `15_fig07_tree_parsimony.R` (preserved, unmodified, inside
#     Analysis/Supplementary.R's block 15) -- also single-ring only.
#
# TO REPRODUCE FIGURE 3 MANUALLY, upload the following files to iTOL:
#   - Tree:     output/ST69/vfdb_analysis/... core-genome tree (see
#               Prerequisites/03c_tree_mapping_vfdb.R for how it is pruned)
#               and output/ST10/vfdb_analysis/pruned_tree.nwk (ST10)
#   - Ring data (per-tip annotations), generated by:
#       - Shell Cluster:  Prerequisites/03c_tree_mapping_vfdb.R (ST69) /
#                         Prerequisites/03d_tree_mapping_vf.R (ST10)
#                         -> tree_cluster_mapping.csv
#       - Clinicality:    source_niche / clinical column in each ST's
#                         metadata (config$st_metadata())
#       - Region/Country: country / continent column in metadata
#       - K-type (ST69):  Analysis/Supplementary.R block for
#                         09d_k_type_analysis.R
#       - Year:           Collection Year column in metadata
#
# No command is fabricated here since none was ever run as an R script for
# this figure. If you'd like an iTOL annotation-file generator (a script
# that writes the per-ring iTOL dataset text files from the CSVs above, so
# only the upload/render step in iTOL itself remains manual), let Claude
# know and it can be added here.
# ==============================================================================

stop(
  "Analysis/Figure3.R is a placeholder. Submitted Figure 3 was built in ",
  "iTOL (confirmed), not by any R script in this repository. See the ",
  "header comment in this file for the upstream data files needed to ",
  "reproduce it manually in iTOL."
)
